// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/quest/ClientOperations.proto

package quest.protocol;

public final class ClientMessage {
  private ClientMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientOperationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .quest.ClientOperation.Type operation = 1;
    boolean hasOperation();
    quest.protocol.ClientMessage.ClientOperation.Type getOperation();
    
    // required uint32 clientId = 2;
    boolean hasClientId();
    int getClientId();
    
    // optional bytes bodyMessage = 3;
    boolean hasBodyMessage();
    com.google.protobuf.ByteString getBodyMessage();
  }
  public static final class ClientOperation extends
      com.google.protobuf.GeneratedMessage
      implements ClientOperationOrBuilder {
    // Use ClientOperation.newBuilder() to construct.
    private ClientOperation(Builder builder) {
      super(builder);
    }
    private ClientOperation(boolean noInit) {}
    
    private static final ClientOperation defaultInstance;
    public static ClientOperation getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClientOperation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return quest.protocol.ClientMessage.internal_static_quest_ClientOperation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return quest.protocol.ClientMessage.internal_static_quest_ClientOperation_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      INPUT(0, 1),
      ;
      
      public static final int INPUT_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return INPUT;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return quest.protocol.ClientMessage.ClientOperation.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        INPUT, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:quest.ClientOperation.Type)
    }
    
    private int bitField0_;
    // required .quest.ClientOperation.Type operation = 1;
    public static final int OPERATION_FIELD_NUMBER = 1;
    private quest.protocol.ClientMessage.ClientOperation.Type operation_;
    public boolean hasOperation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public quest.protocol.ClientMessage.ClientOperation.Type getOperation() {
      return operation_;
    }
    
    // required uint32 clientId = 2;
    public static final int CLIENTID_FIELD_NUMBER = 2;
    private int clientId_;
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getClientId() {
      return clientId_;
    }
    
    // optional bytes bodyMessage = 3;
    public static final int BODYMESSAGE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString bodyMessage_;
    public boolean hasBodyMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getBodyMessage() {
      return bodyMessage_;
    }
    
    private void initFields() {
      operation_ = quest.protocol.ClientMessage.ClientOperation.Type.INPUT;
      clientId_ = 0;
      bodyMessage_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasOperation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, operation_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, clientId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, bodyMessage_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, operation_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, clientId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, bodyMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static quest.protocol.ClientMessage.ClientOperation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static quest.protocol.ClientMessage.ClientOperation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static quest.protocol.ClientMessage.ClientOperation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static quest.protocol.ClientMessage.ClientOperation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static quest.protocol.ClientMessage.ClientOperation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static quest.protocol.ClientMessage.ClientOperation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static quest.protocol.ClientMessage.ClientOperation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static quest.protocol.ClientMessage.ClientOperation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static quest.protocol.ClientMessage.ClientOperation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static quest.protocol.ClientMessage.ClientOperation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(quest.protocol.ClientMessage.ClientOperation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements quest.protocol.ClientMessage.ClientOperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return quest.protocol.ClientMessage.internal_static_quest_ClientOperation_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return quest.protocol.ClientMessage.internal_static_quest_ClientOperation_fieldAccessorTable;
      }
      
      // Construct using quest.protocol.ClientMessage.ClientOperation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        operation_ = quest.protocol.ClientMessage.ClientOperation.Type.INPUT;
        bitField0_ = (bitField0_ & ~0x00000001);
        clientId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        bodyMessage_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return quest.protocol.ClientMessage.ClientOperation.getDescriptor();
      }
      
      public quest.protocol.ClientMessage.ClientOperation getDefaultInstanceForType() {
        return quest.protocol.ClientMessage.ClientOperation.getDefaultInstance();
      }
      
      public quest.protocol.ClientMessage.ClientOperation build() {
        quest.protocol.ClientMessage.ClientOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private quest.protocol.ClientMessage.ClientOperation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        quest.protocol.ClientMessage.ClientOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public quest.protocol.ClientMessage.ClientOperation buildPartial() {
        quest.protocol.ClientMessage.ClientOperation result = new quest.protocol.ClientMessage.ClientOperation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.operation_ = operation_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.bodyMessage_ = bodyMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof quest.protocol.ClientMessage.ClientOperation) {
          return mergeFrom((quest.protocol.ClientMessage.ClientOperation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(quest.protocol.ClientMessage.ClientOperation other) {
        if (other == quest.protocol.ClientMessage.ClientOperation.getDefaultInstance()) return this;
        if (other.hasOperation()) {
          setOperation(other.getOperation());
        }
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasBodyMessage()) {
          setBodyMessage(other.getBodyMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasOperation()) {
          
          return false;
        }
        if (!hasClientId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              quest.protocol.ClientMessage.ClientOperation.Type value = quest.protocol.ClientMessage.ClientOperation.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                operation_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              clientId_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              bodyMessage_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .quest.ClientOperation.Type operation = 1;
      private quest.protocol.ClientMessage.ClientOperation.Type operation_ = quest.protocol.ClientMessage.ClientOperation.Type.INPUT;
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public quest.protocol.ClientMessage.ClientOperation.Type getOperation() {
        return operation_;
      }
      public Builder setOperation(quest.protocol.ClientMessage.ClientOperation.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        operation_ = value;
        onChanged();
        return this;
      }
      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000001);
        operation_ = quest.protocol.ClientMessage.ClientOperation.Type.INPUT;
        onChanged();
        return this;
      }
      
      // required uint32 clientId = 2;
      private int clientId_ ;
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getClientId() {
        return clientId_;
      }
      public Builder setClientId(int value) {
        bitField0_ |= 0x00000002;
        clientId_ = value;
        onChanged();
        return this;
      }
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientId_ = 0;
        onChanged();
        return this;
      }
      
      // optional bytes bodyMessage = 3;
      private com.google.protobuf.ByteString bodyMessage_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasBodyMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getBodyMessage() {
        return bodyMessage_;
      }
      public Builder setBodyMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        bodyMessage_ = value;
        onChanged();
        return this;
      }
      public Builder clearBodyMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bodyMessage_ = getDefaultInstance().getBodyMessage();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:quest.ClientOperation)
    }
    
    static {
      defaultInstance = new ClientOperation(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:quest.ClientOperation)
  }
  
  public interface InputOperationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .quest.InputOperation.Input input = 1;
    java.util.List<quest.protocol.ClientMessage.InputOperation.Input> getInputList();
    int getInputCount();
    quest.protocol.ClientMessage.InputOperation.Input getInput(int index);
  }
  public static final class InputOperation extends
      com.google.protobuf.GeneratedMessage
      implements InputOperationOrBuilder {
    // Use InputOperation.newBuilder() to construct.
    private InputOperation(Builder builder) {
      super(builder);
    }
    private InputOperation(boolean noInit) {}
    
    private static final InputOperation defaultInstance;
    public static InputOperation getDefaultInstance() {
      return defaultInstance;
    }
    
    public InputOperation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return quest.protocol.ClientMessage.internal_static_quest_InputOperation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return quest.protocol.ClientMessage.internal_static_quest_InputOperation_fieldAccessorTable;
    }
    
    public enum Input
        implements com.google.protobuf.ProtocolMessageEnum {
      UP_KEY(0, 1),
      DOWN_KEY(1, 2),
      LEFT_KEY(2, 3),
      RIGHT_KEY(3, 4),
      ;
      
      public static final int UP_KEY_VALUE = 1;
      public static final int DOWN_KEY_VALUE = 2;
      public static final int LEFT_KEY_VALUE = 3;
      public static final int RIGHT_KEY_VALUE = 4;
      
      
      public final int getNumber() { return value; }
      
      public static Input valueOf(int value) {
        switch (value) {
          case 1: return UP_KEY;
          case 2: return DOWN_KEY;
          case 3: return LEFT_KEY;
          case 4: return RIGHT_KEY;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Input>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Input>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Input>() {
              public Input findValueByNumber(int number) {
                return Input.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return quest.protocol.ClientMessage.InputOperation.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Input[] VALUES = {
        UP_KEY, DOWN_KEY, LEFT_KEY, RIGHT_KEY, 
      };
      
      public static Input valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Input(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:quest.InputOperation.Input)
    }
    
    // repeated .quest.InputOperation.Input input = 1;
    public static final int INPUT_FIELD_NUMBER = 1;
    private java.util.List<quest.protocol.ClientMessage.InputOperation.Input> input_;
    public java.util.List<quest.protocol.ClientMessage.InputOperation.Input> getInputList() {
      return input_;
    }
    public int getInputCount() {
      return input_.size();
    }
    public quest.protocol.ClientMessage.InputOperation.Input getInput(int index) {
      return input_.get(index);
    }
    
    private void initFields() {
      input_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < input_.size(); i++) {
        output.writeEnum(1, input_.get(i).getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < input_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(input_.get(i).getNumber());
        }
        size += dataSize;
        size += 1 * input_.size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static quest.protocol.ClientMessage.InputOperation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static quest.protocol.ClientMessage.InputOperation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static quest.protocol.ClientMessage.InputOperation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static quest.protocol.ClientMessage.InputOperation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static quest.protocol.ClientMessage.InputOperation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static quest.protocol.ClientMessage.InputOperation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static quest.protocol.ClientMessage.InputOperation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static quest.protocol.ClientMessage.InputOperation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static quest.protocol.ClientMessage.InputOperation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static quest.protocol.ClientMessage.InputOperation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(quest.protocol.ClientMessage.InputOperation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements quest.protocol.ClientMessage.InputOperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return quest.protocol.ClientMessage.internal_static_quest_InputOperation_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return quest.protocol.ClientMessage.internal_static_quest_InputOperation_fieldAccessorTable;
      }
      
      // Construct using quest.protocol.ClientMessage.InputOperation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        input_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return quest.protocol.ClientMessage.InputOperation.getDescriptor();
      }
      
      public quest.protocol.ClientMessage.InputOperation getDefaultInstanceForType() {
        return quest.protocol.ClientMessage.InputOperation.getDefaultInstance();
      }
      
      public quest.protocol.ClientMessage.InputOperation build() {
        quest.protocol.ClientMessage.InputOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private quest.protocol.ClientMessage.InputOperation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        quest.protocol.ClientMessage.InputOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public quest.protocol.ClientMessage.InputOperation buildPartial() {
        quest.protocol.ClientMessage.InputOperation result = new quest.protocol.ClientMessage.InputOperation(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          input_ = java.util.Collections.unmodifiableList(input_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.input_ = input_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof quest.protocol.ClientMessage.InputOperation) {
          return mergeFrom((quest.protocol.ClientMessage.InputOperation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(quest.protocol.ClientMessage.InputOperation other) {
        if (other == quest.protocol.ClientMessage.InputOperation.getDefaultInstance()) return this;
        if (!other.input_.isEmpty()) {
          if (input_.isEmpty()) {
            input_ = other.input_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInputIsMutable();
            input_.addAll(other.input_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              quest.protocol.ClientMessage.InputOperation.Input value = quest.protocol.ClientMessage.InputOperation.Input.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                addInput(value);
              }
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                quest.protocol.ClientMessage.InputOperation.Input value = quest.protocol.ClientMessage.InputOperation.Input.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  addInput(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .quest.InputOperation.Input input = 1;
      private java.util.List<quest.protocol.ClientMessage.InputOperation.Input> input_ =
        java.util.Collections.emptyList();
      private void ensureInputIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          input_ = new java.util.ArrayList<quest.protocol.ClientMessage.InputOperation.Input>(input_);
          bitField0_ |= 0x00000001;
        }
      }
      public java.util.List<quest.protocol.ClientMessage.InputOperation.Input> getInputList() {
        return java.util.Collections.unmodifiableList(input_);
      }
      public int getInputCount() {
        return input_.size();
      }
      public quest.protocol.ClientMessage.InputOperation.Input getInput(int index) {
        return input_.get(index);
      }
      public Builder setInput(
          int index, quest.protocol.ClientMessage.InputOperation.Input value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInputIsMutable();
        input_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addInput(quest.protocol.ClientMessage.InputOperation.Input value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInputIsMutable();
        input_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllInput(
          java.lang.Iterable<? extends quest.protocol.ClientMessage.InputOperation.Input> values) {
        ensureInputIsMutable();
        super.addAll(values, input_);
        onChanged();
        return this;
      }
      public Builder clearInput() {
        input_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:quest.InputOperation)
    }
    
    static {
      defaultInstance = new InputOperation(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:quest.InputOperation)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_quest_ClientOperation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_quest_ClientOperation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_quest_InputOperation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_quest_InputOperation_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/src/main/resources/quest/ClientOperati" +
      "ons.proto\022\005quest\032%src/main/resources/que" +
      "st/Common.proto\"{\n\017ClientOperation\022.\n\top" +
      "eration\030\001 \002(\0162\033.quest.ClientOperation.Ty" +
      "pe\022\020\n\010clientId\030\002 \002(\r\022\023\n\013bodyMessage\030\003 \001(" +
      "\014\"\021\n\004Type\022\t\n\005INPUT\020\001\"|\n\016InputOperation\022*" +
      "\n\005input\030\001 \003(\0162\033.quest.InputOperation.Inp" +
      "ut\">\n\005Input\022\n\n\006UP_KEY\020\001\022\014\n\010DOWN_KEY\020\002\022\014\n" +
      "\010LEFT_KEY\020\003\022\r\n\tRIGHT_KEY\020\004B\037\n\016quest.prot" +
      "ocolB\rClientMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_quest_ClientOperation_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_quest_ClientOperation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_quest_ClientOperation_descriptor,
              new java.lang.String[] { "Operation", "ClientId", "BodyMessage", },
              quest.protocol.ClientMessage.ClientOperation.class,
              quest.protocol.ClientMessage.ClientOperation.Builder.class);
          internal_static_quest_InputOperation_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_quest_InputOperation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_quest_InputOperation_descriptor,
              new java.lang.String[] { "Input", },
              quest.protocol.ClientMessage.InputOperation.class,
              quest.protocol.ClientMessage.InputOperation.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          quest.protocol.СommonMessages.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
