// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/quest/GameServerOperations.proto

package quest.protocol;

public final class GameServerMessage {
  private GameServerMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GameServerOperationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .quest.GameServerOperation.Type operation = 1;
    boolean hasOperation();
    quest.protocol.GameServerMessage.GameServerOperation.Type getOperation();
    
    // required bytes bodyMessage = 2;
    boolean hasBodyMessage();
    com.google.protobuf.ByteString getBodyMessage();
  }
  public static final class GameServerOperation extends
      com.google.protobuf.GeneratedMessage
      implements GameServerOperationOrBuilder {
    // Use GameServerOperation.newBuilder() to construct.
    private GameServerOperation(Builder builder) {
      super(builder);
    }
    private GameServerOperation(boolean noInit) {}
    
    private static final GameServerOperation defaultInstance;
    public static GameServerOperation getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameServerOperation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return quest.protocol.GameServerMessage.internal_static_quest_GameServerOperation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return quest.protocol.GameServerMessage.internal_static_quest_GameServerOperation_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      DELTA(0, 1),
      ;
      
      public static final int DELTA_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return DELTA;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return quest.protocol.GameServerMessage.GameServerOperation.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        DELTA, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:quest.GameServerOperation.Type)
    }
    
    private int bitField0_;
    // required .quest.GameServerOperation.Type operation = 1;
    public static final int OPERATION_FIELD_NUMBER = 1;
    private quest.protocol.GameServerMessage.GameServerOperation.Type operation_;
    public boolean hasOperation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public quest.protocol.GameServerMessage.GameServerOperation.Type getOperation() {
      return operation_;
    }
    
    // required bytes bodyMessage = 2;
    public static final int BODYMESSAGE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString bodyMessage_;
    public boolean hasBodyMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getBodyMessage() {
      return bodyMessage_;
    }
    
    private void initFields() {
      operation_ = quest.protocol.GameServerMessage.GameServerOperation.Type.DELTA;
      bodyMessage_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasOperation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBodyMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, operation_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, bodyMessage_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, operation_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, bodyMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static quest.protocol.GameServerMessage.GameServerOperation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static quest.protocol.GameServerMessage.GameServerOperation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static quest.protocol.GameServerMessage.GameServerOperation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static quest.protocol.GameServerMessage.GameServerOperation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static quest.protocol.GameServerMessage.GameServerOperation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static quest.protocol.GameServerMessage.GameServerOperation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static quest.protocol.GameServerMessage.GameServerOperation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static quest.protocol.GameServerMessage.GameServerOperation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static quest.protocol.GameServerMessage.GameServerOperation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static quest.protocol.GameServerMessage.GameServerOperation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(quest.protocol.GameServerMessage.GameServerOperation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements quest.protocol.GameServerMessage.GameServerOperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return quest.protocol.GameServerMessage.internal_static_quest_GameServerOperation_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return quest.protocol.GameServerMessage.internal_static_quest_GameServerOperation_fieldAccessorTable;
      }
      
      // Construct using quest.protocol.GameServerMessage.GameServerOperation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        operation_ = quest.protocol.GameServerMessage.GameServerOperation.Type.DELTA;
        bitField0_ = (bitField0_ & ~0x00000001);
        bodyMessage_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return quest.protocol.GameServerMessage.GameServerOperation.getDescriptor();
      }
      
      public quest.protocol.GameServerMessage.GameServerOperation getDefaultInstanceForType() {
        return quest.protocol.GameServerMessage.GameServerOperation.getDefaultInstance();
      }
      
      public quest.protocol.GameServerMessage.GameServerOperation build() {
        quest.protocol.GameServerMessage.GameServerOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private quest.protocol.GameServerMessage.GameServerOperation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        quest.protocol.GameServerMessage.GameServerOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public quest.protocol.GameServerMessage.GameServerOperation buildPartial() {
        quest.protocol.GameServerMessage.GameServerOperation result = new quest.protocol.GameServerMessage.GameServerOperation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.operation_ = operation_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bodyMessage_ = bodyMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof quest.protocol.GameServerMessage.GameServerOperation) {
          return mergeFrom((quest.protocol.GameServerMessage.GameServerOperation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(quest.protocol.GameServerMessage.GameServerOperation other) {
        if (other == quest.protocol.GameServerMessage.GameServerOperation.getDefaultInstance()) return this;
        if (other.hasOperation()) {
          setOperation(other.getOperation());
        }
        if (other.hasBodyMessage()) {
          setBodyMessage(other.getBodyMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasOperation()) {
          
          return false;
        }
        if (!hasBodyMessage()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              quest.protocol.GameServerMessage.GameServerOperation.Type value = quest.protocol.GameServerMessage.GameServerOperation.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                operation_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              bodyMessage_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .quest.GameServerOperation.Type operation = 1;
      private quest.protocol.GameServerMessage.GameServerOperation.Type operation_ = quest.protocol.GameServerMessage.GameServerOperation.Type.DELTA;
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public quest.protocol.GameServerMessage.GameServerOperation.Type getOperation() {
        return operation_;
      }
      public Builder setOperation(quest.protocol.GameServerMessage.GameServerOperation.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        operation_ = value;
        onChanged();
        return this;
      }
      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000001);
        operation_ = quest.protocol.GameServerMessage.GameServerOperation.Type.DELTA;
        onChanged();
        return this;
      }
      
      // required bytes bodyMessage = 2;
      private com.google.protobuf.ByteString bodyMessage_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasBodyMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getBodyMessage() {
        return bodyMessage_;
      }
      public Builder setBodyMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bodyMessage_ = value;
        onChanged();
        return this;
      }
      public Builder clearBodyMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bodyMessage_ = getDefaultInstance().getBodyMessage();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:quest.GameServerOperation)
    }
    
    static {
      defaultInstance = new GameServerOperation(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:quest.GameServerOperation)
  }
  
  public interface GameStateOperationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .User user = 1;
    java.util.List<quest.protocol.СommonMessages.User> 
        getUserList();
    quest.protocol.СommonMessages.User getUser(int index);
    int getUserCount();
    java.util.List<? extends quest.protocol.СommonMessages.UserOrBuilder> 
        getUserOrBuilderList();
    quest.protocol.СommonMessages.UserOrBuilder getUserOrBuilder(
        int index);
  }
  public static final class GameStateOperation extends
      com.google.protobuf.GeneratedMessage
      implements GameStateOperationOrBuilder {
    // Use GameStateOperation.newBuilder() to construct.
    private GameStateOperation(Builder builder) {
      super(builder);
    }
    private GameStateOperation(boolean noInit) {}
    
    private static final GameStateOperation defaultInstance;
    public static GameStateOperation getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameStateOperation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return quest.protocol.GameServerMessage.internal_static_quest_GameStateOperation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return quest.protocol.GameServerMessage.internal_static_quest_GameStateOperation_fieldAccessorTable;
    }
    
    // repeated .User user = 1;
    public static final int USER_FIELD_NUMBER = 1;
    private java.util.List<quest.protocol.СommonMessages.User> user_;
    public java.util.List<quest.protocol.СommonMessages.User> getUserList() {
      return user_;
    }
    public java.util.List<? extends quest.protocol.СommonMessages.UserOrBuilder> 
        getUserOrBuilderList() {
      return user_;
    }
    public int getUserCount() {
      return user_.size();
    }
    public quest.protocol.СommonMessages.User getUser(int index) {
      return user_.get(index);
    }
    public quest.protocol.СommonMessages.UserOrBuilder getUserOrBuilder(
        int index) {
      return user_.get(index);
    }
    
    private void initFields() {
      user_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getUserCount(); i++) {
        if (!getUser(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < user_.size(); i++) {
        output.writeMessage(1, user_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < user_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, user_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static quest.protocol.GameServerMessage.GameStateOperation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static quest.protocol.GameServerMessage.GameStateOperation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static quest.protocol.GameServerMessage.GameStateOperation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static quest.protocol.GameServerMessage.GameStateOperation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static quest.protocol.GameServerMessage.GameStateOperation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static quest.protocol.GameServerMessage.GameStateOperation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static quest.protocol.GameServerMessage.GameStateOperation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static quest.protocol.GameServerMessage.GameStateOperation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static quest.protocol.GameServerMessage.GameStateOperation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static quest.protocol.GameServerMessage.GameStateOperation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(quest.protocol.GameServerMessage.GameStateOperation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements quest.protocol.GameServerMessage.GameStateOperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return quest.protocol.GameServerMessage.internal_static_quest_GameStateOperation_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return quest.protocol.GameServerMessage.internal_static_quest_GameStateOperation_fieldAccessorTable;
      }
      
      // Construct using quest.protocol.GameServerMessage.GameStateOperation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          userBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return quest.protocol.GameServerMessage.GameStateOperation.getDescriptor();
      }
      
      public quest.protocol.GameServerMessage.GameStateOperation getDefaultInstanceForType() {
        return quest.protocol.GameServerMessage.GameStateOperation.getDefaultInstance();
      }
      
      public quest.protocol.GameServerMessage.GameStateOperation build() {
        quest.protocol.GameServerMessage.GameStateOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private quest.protocol.GameServerMessage.GameStateOperation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        quest.protocol.GameServerMessage.GameStateOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public quest.protocol.GameServerMessage.GameStateOperation buildPartial() {
        quest.protocol.GameServerMessage.GameStateOperation result = new quest.protocol.GameServerMessage.GameStateOperation(this);
        int from_bitField0_ = bitField0_;
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            user_ = java.util.Collections.unmodifiableList(user_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof quest.protocol.GameServerMessage.GameStateOperation) {
          return mergeFrom((quest.protocol.GameServerMessage.GameStateOperation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(quest.protocol.GameServerMessage.GameStateOperation other) {
        if (other == quest.protocol.GameServerMessage.GameStateOperation.getDefaultInstance()) return this;
        if (userBuilder_ == null) {
          if (!other.user_.isEmpty()) {
            if (user_.isEmpty()) {
              user_ = other.user_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUserIsMutable();
              user_.addAll(other.user_);
            }
            onChanged();
          }
        } else {
          if (!other.user_.isEmpty()) {
            if (userBuilder_.isEmpty()) {
              userBuilder_.dispose();
              userBuilder_ = null;
              user_ = other.user_;
              bitField0_ = (bitField0_ & ~0x00000001);
              userBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUserFieldBuilder() : null;
            } else {
              userBuilder_.addAllMessages(other.user_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getUserCount(); i++) {
          if (!getUser(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              quest.protocol.СommonMessages.User.Builder subBuilder = quest.protocol.СommonMessages.User.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addUser(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .User user = 1;
      private java.util.List<quest.protocol.СommonMessages.User> user_ =
        java.util.Collections.emptyList();
      private void ensureUserIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          user_ = new java.util.ArrayList<quest.protocol.СommonMessages.User>(user_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          quest.protocol.СommonMessages.User, quest.protocol.СommonMessages.User.Builder, quest.protocol.СommonMessages.UserOrBuilder> userBuilder_;
      
      public java.util.List<quest.protocol.СommonMessages.User> getUserList() {
        if (userBuilder_ == null) {
          return java.util.Collections.unmodifiableList(user_);
        } else {
          return userBuilder_.getMessageList();
        }
      }
      public int getUserCount() {
        if (userBuilder_ == null) {
          return user_.size();
        } else {
          return userBuilder_.getCount();
        }
      }
      public quest.protocol.СommonMessages.User getUser(int index) {
        if (userBuilder_ == null) {
          return user_.get(index);
        } else {
          return userBuilder_.getMessage(index);
        }
      }
      public Builder setUser(
          int index, quest.protocol.СommonMessages.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.set(index, value);
          onChanged();
        } else {
          userBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setUser(
          int index, quest.protocol.СommonMessages.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.set(index, builderForValue.build());
          onChanged();
        } else {
          userBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addUser(quest.protocol.СommonMessages.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.add(value);
          onChanged();
        } else {
          userBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addUser(
          int index, quest.protocol.СommonMessages.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.add(index, value);
          onChanged();
        } else {
          userBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addUser(
          quest.protocol.СommonMessages.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.add(builderForValue.build());
          onChanged();
        } else {
          userBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addUser(
          int index, quest.protocol.СommonMessages.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.add(index, builderForValue.build());
          onChanged();
        } else {
          userBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllUser(
          java.lang.Iterable<? extends quest.protocol.СommonMessages.User> values) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          super.addAll(values, user_);
          onChanged();
        } else {
          userBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          userBuilder_.clear();
        }
        return this;
      }
      public Builder removeUser(int index) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.remove(index);
          onChanged();
        } else {
          userBuilder_.remove(index);
        }
        return this;
      }
      public quest.protocol.СommonMessages.User.Builder getUserBuilder(
          int index) {
        return getUserFieldBuilder().getBuilder(index);
      }
      public quest.protocol.СommonMessages.UserOrBuilder getUserOrBuilder(
          int index) {
        if (userBuilder_ == null) {
          return user_.get(index);  } else {
          return userBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends quest.protocol.СommonMessages.UserOrBuilder> 
           getUserOrBuilderList() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(user_);
        }
      }
      public quest.protocol.СommonMessages.User.Builder addUserBuilder() {
        return getUserFieldBuilder().addBuilder(
            quest.protocol.СommonMessages.User.getDefaultInstance());
      }
      public quest.protocol.СommonMessages.User.Builder addUserBuilder(
          int index) {
        return getUserFieldBuilder().addBuilder(
            index, quest.protocol.СommonMessages.User.getDefaultInstance());
      }
      public java.util.List<quest.protocol.СommonMessages.User.Builder> 
           getUserBuilderList() {
        return getUserFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          quest.protocol.СommonMessages.User, quest.protocol.СommonMessages.User.Builder, quest.protocol.СommonMessages.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              quest.protocol.СommonMessages.User, quest.protocol.СommonMessages.User.Builder, quest.protocol.СommonMessages.UserOrBuilder>(
                  user_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:quest.GameStateOperation)
    }
    
    static {
      defaultInstance = new GameStateOperation(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:quest.GameStateOperation)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_quest_GameServerOperation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_quest_GameServerOperation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_quest_GameStateOperation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_quest_GameStateOperation_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3src/main/resources/quest/GameServerOpe" +
      "rations.proto\022\005quest\032%src/main/resources" +
      "/quest/Common.proto\"q\n\023GameServerOperati" +
      "on\0222\n\toperation\030\001 \002(\0162\037.quest.GameServer" +
      "Operation.Type\022\023\n\013bodyMessage\030\002 \002(\014\"\021\n\004T" +
      "ype\022\t\n\005DELTA\020\001\")\n\022GameStateOperation\022\023\n\004" +
      "user\030\001 \003(\0132\005.UserB#\n\016quest.protocolB\021Gam" +
      "eServerMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_quest_GameServerOperation_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_quest_GameServerOperation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_quest_GameServerOperation_descriptor,
              new java.lang.String[] { "Operation", "BodyMessage", },
              quest.protocol.GameServerMessage.GameServerOperation.class,
              quest.protocol.GameServerMessage.GameServerOperation.Builder.class);
          internal_static_quest_GameStateOperation_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_quest_GameStateOperation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_quest_GameStateOperation_descriptor,
              new java.lang.String[] { "User", },
              quest.protocol.GameServerMessage.GameStateOperation.class,
              quest.protocol.GameServerMessage.GameStateOperation.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          quest.protocol.СommonMessages.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
